# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Carseat.create(name: “Century Carry On 35 LX”, mode: “rear”, expiration: 7,  price: 112, features: “2 sets harness loops, infant padding”, img: "https://csftl.org/wp-content/uploads/2023/04/century_carry_on.png")
Carseat.create(name: “Cosco Light n Comfy”, mode: “infant”, expiration: 8, price: 160, features: “nil”, img: "https://csftl.org/wp-content/uploads/2017/09/cosco-lightncomfydxinfantcarseat-150x150.jpg")
Carseat.create(name: “Safety 1st OnBoard 35 LT”, mode: “rear”, expiration:  8, price: 130, features: “large canopy”, img: "https://csftl.org/wp-content/uploads/2017/09/safety1st-onboardtm-35-lt-150x150.jpg")
Carseat.create(name: “Graco SnugRide 35 Lite”, mode: “rear”, expiration: 7, price: 110, features: “allows European routing for baseless installation”, img: "https://csftl.org/wp-content/uploads/2020/08/Graco-SnugRide-Lite-recbanner-150x150.png")
Carseat.create(name: “Evenflo LiteMax Sport”, mode: “rear”, expiration: 7,  price: 126, features: “Buckle tongue storage and lockoff. Buckle tongue storage and lockoff.”, img: "https://csftl.org/wp-content/uploads/2019/11/EvenfloLiteMaxrecbanner-150x150.png")
Carseat.create(name: “Graco SnugRide SnugLock Series”, mode: “rear”, expiration: 7, price: 95, features: “premium connectors, adjustable base, no rethread harness” img: "https://csftl.org/wp-content/uploads/2020/08/Graco-SnugRide-Lite-recbanner-150x150.png")
Carseat.create(name: “Chicco KeyFit 35”, mode: “rear”, expiration: 6,  price: 250, features: “allows European routing for baseless installation, anti rebound bar, lockout”, img: "https://csftl.org/wp-content/uploads/2019/11/EvenfloLiteMaxrecbanner-150x150.png")
Carseat.create(name: “Nuna Pipa”, mode: “rear”, expiration: 7, price: 400, features: “Allows European routing for baseless installation, dream drape canopy, harness pads, load leg, lockoff, and rigid lower anchor connectors”, img: "https://csftl.org/wp-content/uploads/2017/09/nuna-pipa-150x150.jpg")
Carseat.create(name: “Evenflo Shyft DualRide”, mode: “rear”, expiration:  6, price: 550, features: “is also a stroller”, img: "https://csftl.org/wp-content/uploads/2023/04/evenflo-shyft-dualride.webp")
Carseat.create(name: “Cosco Scenery Next”, mode: “rear, forward”, expiration: 8, price: 60, features: “optional cup holder”, img: "https://csftl.org/wp-content/uploads/2017/09/cosco-sceneranextconvertiblecarseat-renaissance-cc140azs-renaisance-bty-r-072315-150x150.jpg" )
Carseat.create(name: “Evenflo Songs”, mode: “rear, forward”, expiration: 6,  price: 126, features: “dual cupholders”, img: "https://csftl.org/wp-content/uploads/2017/09/evenflo-sonus-150x150.jpg")
Carseat.create(name: “Graco Contender and Admiral 65”, mode: “rear, forward”, expiration: 7, price: 170, features: “no rethread harness, single cupholder”, img: "https://csftl.org/wp-content/uploads/2017/09/graco-contender-150x150.jpg")
Carseat.create(name: “Graco Extend2Fit Convertible”, mode: “rear, forward”, expiration:  10, price: 200, features: “extra 5in legroom, dual cupholders, no rethread harness”, img: "https://csftl.org/wp-content/uploads/2017/09/graco-extend2fit-conv-150x150.jpg")
Carseat.create(name: “Britax Emblem and Allegiance”, mode: “rear, forward”, expiration: 7, price: 230, features: “carry handle, lockoff, no rethread, EZ buckle holds harness in place when buckling”, img: "https://csftl.org/wp-content/uploads/2018/04/530ED04E-07A6-40FF-A70B-C0EFBFBF0163-150x150.jpeg")
Carseat.create(name: “Chicco Nexfit”, mode: “rear, forward”, expiration:  8, price: 320, features: “easy cover removal, no rethread, premium anchors, lockoffs”, img: "https://csftl.org/wp-content/uploads/2017/09/Chicco-NextFit-150x150.jpg")
Carseat.create(name: “Britax ClickTight Convertables”, mode: “rear, forward”, expiration: 10, price: 240, features: “anti rebound bar, click tight installation, EZ buckle holds, lockoffs, no rethread”, img: "https://csftl.org/wp-content/uploads/2018/01/britax-boulevard-clicktight-1-150x150.jpg")
Carseat.create(name: “Nuna Rava”, mode: “rear, forward”, expiration: 10,  price: 550, features: “buckle tongue holders, adds 2in leg room, no rethread, tension installation”, img: "https://csftl.org/wp-content/uploads/2017/09/nuna-rava-150x150.jpg")
Carseat.create(name: "Century Drive On", mode: "rear, forward, booster", expiration: 10, price: 121, features: "hideaway harness, dual cuphodlers, no rethread", img: "https://csftl.org/wp-content/uploads/2021/12/Century_DriveOn_recbanner-150x150.png")
Carseat.create(name: "Graco TrioGrow SnugLock", mode: "rear, forward, booster", expiration: 10, price: 200, features: "rapid remove cover, cupholders, hideaway harness, premium conectors", img: "https://csftl.org/wp-content/uploads/2020/07/Graco-TrioGrow-recbanner-150x150.png")
Carseat.create(name: "Graco Extend2Fit 3-in-1", mode: "rear, forward, booster", expiration: 10, price: 250, features: "5in extra leg room, cupholders, hideaway harness, premium conectors", img: "https://csftl.org/wp-content/uploads/2020/12/Graco-Extend2Fit3in1-recbanner-150x150.png")
Carseat.create(name: "Graco SlimFit3 LX and True3Fit LX", mode: "rear, forward, booster", expiration: 10, price: 280, features: "three across friendly, rapid remove cover, no rethread, premium connectors, hideaway harness", img: "https://csftl.org/wp-content/uploads/2021/01/Graco-SlimFit3LX-recbanner-150x150.png")
Carseat.create(name: 'Graco 4Ever DLX', mode: 'rear, forward, booster', expiration: 10, price: 250, features: 'cupholders, lockoff, hideaway harness, rapid remove cover, premium connectors', img: "https://csftl.org/wp-content/uploads/2020/12/Graco-4EverDLX-recbanner-150x150.png")